-- Seed all checklists
DO $$
DECLARE
  v_tmpl_id UUID;
BEGIN

  -- 1. TESOURA
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Tesoura', 'Tesoura') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) VALUES
  (v_tmpl_id, 'Sala', 'Vistoria de Tomadas', 1),
  (v_tmpl_id, 'Sala', 'Vistoria de Roteador de internet', 2),
  (v_tmpl_id, 'Sala', 'Vistoria de Iluminação', 3),
  (v_tmpl_id, 'Sala', 'Vistoria de Ventiladores', 4),
  (v_tmpl_id, 'Sala', 'Vistoria de Abajur', 5),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Pias/Sifão e Válvula', 6),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Torneiras', 7),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Registros', 8),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Fluxo de água nas Torneiras', 9),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Fogão', 10),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Geladeira', 11),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Tomadas', 12),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Iluminação', 13),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Ventiladores', 14),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Abajur', 15),
  (v_tmpl_id, 'Suite 1', 'TV', 16),
  (v_tmpl_id, 'Suite 1', 'Controle', 17),
  (v_tmpl_id, 'Suite 1', 'Frigobar', 18),
  (v_tmpl_id, 'Suite 1', 'Torneiras dos Banheiro', 19),
  (v_tmpl_id, 'Suite 1', 'Vaso do Banheiro', 20),
  (v_tmpl_id, 'Suite 1', 'Chuveiro Quente do Banheiro', 21),
  (v_tmpl_id, 'Suite 1', 'Chuveiro Frio do Banheiro', 22),
  (v_tmpl_id, 'Suite 1', 'Disjuntores', 23),
  (v_tmpl_id, 'Suite 1', 'Cifão do Banheiro', 24),
  (v_tmpl_id, 'Suite 1', 'Ducha do Banheiro', 25),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Tomadas', 26),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Roteador de internet', 27),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Iluminação', 28),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Ventiladores', 29),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Abajur', 30),
  (v_tmpl_id, 'Suite 2', 'TV', 31),
  (v_tmpl_id, 'Suite 2', 'Controle', 32),
  (v_tmpl_id, 'Suite 2', 'Frigobar', 33),
  (v_tmpl_id, 'Suite 2', 'Torneiras dos Banheiro', 34),
  (v_tmpl_id, 'Suite 2', 'Vaso do Banheiro', 35),
  (v_tmpl_id, 'Suite 2', 'Chuveiro Quente do Banheiro', 36),
  (v_tmpl_id, 'Suite 2', 'Chuveiro Frio do Banheiro', 37),
  (v_tmpl_id, 'Suite 2', 'Disjuntores', 38),
  (v_tmpl_id, 'Suite 2', 'Cifão do Banheiro', 39),
  (v_tmpl_id, 'Suite 2', 'Ducha do Banheiro', 40),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Tomadas', 41),
  (v_tmpl_id, 'Suite 3', 'Vistoria de Iluminação', 42),
  (v_tmpl_id, 'Suite 3', 'Vistoria de Ventiladores', 43),
  (v_tmpl_id, 'Suite 3', 'Vistoria de Abajur', 44),
  (v_tmpl_id, 'Suite 3', 'TV', 45),
  (v_tmpl_id, 'Suite 3', 'Controle', 46),
  (v_tmpl_id, 'Suite 3', 'Frigobar', 47),
  (v_tmpl_id, 'Suite 3', 'Torneiras dos Banheiro', 48),
  (v_tmpl_id, 'Suite 3', 'Vaso do Banheiro', 49),
  (v_tmpl_id, 'Suite 3', 'Chuveiro Quente do Banheiro', 50),
  (v_tmpl_id, 'Suite 3', 'Chuveiro Frio do Banheiro', 51),
  (v_tmpl_id, 'Suite 3', 'Disjuntores', 52),
  (v_tmpl_id, 'Suite 3', 'Cifão do Banheiro', 53),
  (v_tmpl_id, 'Suite 3', 'Ducha do Banheiro', 54),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Tomadas', 55),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Iluminação', 56),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Pias/Sifão e Válvula', 57),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Torneiras/Quente e Fria', 58),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Registros', 59),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Fluxo de Água nas Torneiras', 60),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Fluxo de Água dos Chuveiros /Qquente e Fria', 61),
  (v_tmpl_id, 'Banheiros', 'Vistoria Ducha Higiênicas', 62),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Vaso Sanitários', 63),
  (v_tmpl_id, 'Banheiros', 'Vistoria dos Telhados', 64),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Tampa de Vaso', 65),
  (v_tmpl_id, 'Banheiros', 'Duchas', 66),
  (v_tmpl_id, 'Extras', 'Tampas de Caixa de Passagem', 67),
  (v_tmpl_id, 'Extras', 'Pingueiras ou Goteiras', 68),
  (v_tmpl_id, 'Extras', 'Pendente Cama', 69),
  (v_tmpl_id, 'Extras', 'TV', 70),
  (v_tmpl_id, 'Extras', 'Ar Condicionado', 71),
  (v_tmpl_id, 'Extras', 'Controle', 72),
  (v_tmpl_id, 'Extras', 'Tomadas', 73),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Pias/Sifão e Válvula', 74),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Torneiras', 75),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Registros', 76),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Fluxo de Água nas Torneiras', 77),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Tomadas', 78),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Iluminação', 79),
  (v_tmpl_id, 'Áreas externas', 'Aquecedor de Água', 80),
  (v_tmpl_id, 'Áreas externas', 'Caixa de Gordura', 81),
  (v_tmpl_id, 'Áreas externas', 'Caixa de Passagem', 82);

  -- 2. COQUEIRO (Structure similar to Tesoura)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Coqueiro', 'Coqueiro') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) VALUES
  (v_tmpl_id, 'Sala', 'Vistoria de Tomadas', 1),
  (v_tmpl_id, 'Sala', 'Vistoria de Roteador de internet', 2),
  (v_tmpl_id, 'Sala', 'Vistoria de Iluminação', 3),
  (v_tmpl_id, 'Sala', 'Vistoria de Ventiladores', 4),
  (v_tmpl_id, 'Sala', 'Vistoria de Abajur', 5),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Pias/Sifão e Válvula', 6),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Torneiras', 7),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Registros', 8),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Fluxo de Água nas Torneiras', 9),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Fogão', 10),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Geladeira', 11),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Tomadas', 12),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Roteador de internet', 13),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Iluminação', 14),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Ventiladores', 15),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Abajur', 16),
  (v_tmpl_id, 'Suite 1', 'TV', 17),
  (v_tmpl_id, 'Suite 1', 'Controle', 18),
  (v_tmpl_id, 'Suite 1', 'Frigobar', 19),
  (v_tmpl_id, 'Suite 1', 'Torneiras dos Banheiro', 20),
  (v_tmpl_id, 'Suite 1', 'Vaso do Banheiro', 21),
  (v_tmpl_id, 'Suite 1', 'Chuveiro Quente do Banheiro', 22),
  (v_tmpl_id, 'Suite 1', 'Chuveiro Frio do Banheiro', 23),
  (v_tmpl_id, 'Suite 1', 'Disjuntores', 24),
  (v_tmpl_id, 'Suite 1', 'Cifão do Banheiro', 25),
  (v_tmpl_id, 'Suite 1', 'Ducha do Banheiro', 26),
  (v_tmpl_id, 'Suite 1', 'Vistoria de Tomadas', 27),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Roteador de internet', 28),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Iluminação', 29),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Ventiladores', 30),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Abajur', 31),
  (v_tmpl_id, 'Suite 2', 'TV', 32),
  (v_tmpl_id, 'Suite 2', 'Controle', 33),
  (v_tmpl_id, 'Suite 2', 'Frigobar', 34),
  (v_tmpl_id, 'Suite 2', 'Torneiras dos Banheiro', 35),
  (v_tmpl_id, 'Suite 2', 'Vaso do Banheiro', 36),
  (v_tmpl_id, 'Suite 2', 'Chuveiro Quente do Banheiro', 37),
  (v_tmpl_id, 'Suite 2', 'Chuveiro Frio do Banheiro', 38),
  (v_tmpl_id, 'Suite 2', 'Disjuntores', 39),
  (v_tmpl_id, 'Suite 2', 'Cifão do Banheiro', 40),
  (v_tmpl_id, 'Suite 2', 'Ducha do Banheiro', 41),
  (v_tmpl_id, 'Suite 2', 'Vistoria de Tomadas', 42),
  (v_tmpl_id, 'Suite 3', 'Vistoria de Roteador de internet', 43),
  (v_tmpl_id, 'Suite 3', 'Vistoria de Iluminação', 44),
  (v_tmpl_id, 'Suite 3', 'Vistoria de Ventiladores', 45),
  (v_tmpl_id, 'Suite 3', 'Vistoria de Abajur', 46),
  (v_tmpl_id, 'Suite 3', 'TV', 47),
  (v_tmpl_id, 'Suite 3', 'Controle', 48),
  (v_tmpl_id, 'Suite 3', 'Frigobar', 49),
  (v_tmpl_id, 'Suite 3', 'Torneiras dos Banheiro', 50),
  (v_tmpl_id, 'Suite 3', 'Vaso do Banheiro', 51),
  (v_tmpl_id, 'Suite 3', 'Chuveiro Quente do Banheiro', 52),
  (v_tmpl_id, 'Suite 3', 'Chuveiro Frio do Banheiro', 53),
  (v_tmpl_id, 'Suite 3', 'Disjuntores', 54),
  (v_tmpl_id, 'Suite 3', 'Cifão do Banheiro', 55),
  (v_tmpl_id, 'Suite 3', 'Ducha do Banheiro', 56),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Tomadas', 57),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Iluminação', 58),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Pias/Sifão e Válvula', 59),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Torneiras/Quente e Fria', 60),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Registros', 61),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Fluxo de Água nas Torneiras', 62),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Fluxo de Água dos Chuveiros /Qquente e Fria', 63),
  (v_tmpl_id, 'Banheiros', 'Vistoria Ducha Higiênicas', 64),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Vaso Sanitários', 65),
  (v_tmpl_id, 'Banheiros', 'Vistoria dos Telhados', 66),
  (v_tmpl_id, 'Banheiros', 'Vistoria de Tampa de Vaso', 67),
  (v_tmpl_id, 'Banheiros', 'Duchas', 68),
  (v_tmpl_id, 'Extras', 'Tampas de Caixa de Passagem', 69),
  (v_tmpl_id, 'Extras', 'Pingueiras ou Goteiras', 70),
  (v_tmpl_id, 'Extras', 'Pendente Cama', 71),
  (v_tmpl_id, 'Extras', 'TV', 72),
  (v_tmpl_id, 'Extras', 'Ar Condicionado', 73),
  (v_tmpl_id, 'Extras', 'Controle', 74),
  (v_tmpl_id, 'Extras', 'Tomadas', 75),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Pias/Sifão e Válvula', 76),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Torneiras', 77),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Registros', 78),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Fluxo de Água nas Torneiras', 79),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Tomadas', 80),
  (v_tmpl_id, 'Áreas externas', 'Vistoria de Iluminação', 81),
  (v_tmpl_id, 'Áreas externas', 'Aquecedor de Água', 82),
  (v_tmpl_id, 'Áreas externas', 'Caixa de Gordura', 83),
  (v_tmpl_id, 'Áreas externas', 'Caixa de Passagem', 84);

  -- 3. CAJUEIRO (Copy of Coqueiro Structure)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Cajueiro', 'Cajueiro') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) 
  SELECT v_tmpl_id, area, description, item_order 
  FROM public.checklist_items    -- Copy from last inserted items (Coqueiro is safest standard)
  WHERE template_id = (SELECT id FROM public.checklist_templates WHERE name = 'Vistoria Completa - Coqueiro');

  -- 4. IGREJA (Copy of Coqueiro Structure)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Igreja', 'Igreja') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) 
  SELECT v_tmpl_id, area, description, item_order 
  FROM public.checklist_items 
  WHERE template_id = (SELECT id FROM public.checklist_templates WHERE name = 'Vistoria Completa - Coqueiro');

  -- 5. MARIA PRAÇA (Copy of Coqueiro Structure)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Maria Praça', 'Maria Praça') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) 
  SELECT v_tmpl_id, area, description, item_order 
  FROM public.checklist_items 
  WHERE template_id = (SELECT id FROM public.checklist_templates WHERE name = 'Vistoria Completa - Coqueiro');
  
  -- 6. MARIA RIO (Copy of Coqueiro Structure)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Maria Rio', 'Maria Rio') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) 
  SELECT v_tmpl_id, area, description, item_order 
  FROM public.checklist_items 
  WHERE template_id = (SELECT id FROM public.checklist_templates WHERE name = 'Vistoria Completa - Coqueiro');

  -- 7. COBOGÓ (Copy of Coqueiro Structure)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Cobogó', 'Cobogó') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) 
  SELECT v_tmpl_id, area, description, item_order 
  FROM public.checklist_items 
  WHERE template_id = (SELECT id FROM public.checklist_templates WHERE name = 'Vistoria Completa - Coqueiro');

  -- 8. HOSPEDARIA (Copy of Coqueiro Structure but check if there are minor diffs, looks identical in list)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Hopedaria', 'Hopedaria') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) 
  SELECT v_tmpl_id, area, description, item_order 
  FROM public.checklist_items 
  WHERE template_id = (SELECT id FROM public.checklist_templates WHERE name = 'Vistoria Completa - Coqueiro');

  -- 9. ÁREA ANCORADOURO (Custom Structure)
  INSERT INTO public.checklist_templates (name, location) VALUES ('Vistoria Completa - Área Ancoradouro', 'Área Ancoradouro') RETURNING id INTO v_tmpl_id;
  INSERT INTO public.checklist_items (template_id, area, description, item_order) VALUES
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de tomadas', 1),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de Roteador de internet', 2),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de iluminação', 3),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de ventiladores', 4),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de abajur', 5),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de Ar Condicionado', 6),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria das dobradiças', 7),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria dos móveis', 8),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de Pias/sifão e válvula', 9),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de torneiras', 10),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de registros', 11),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de fluxo de água dos chuveiros/quente e fria', 12),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de fluxo de água nas torneiras/quente e fria', 13),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria ducha higiênicas', 14),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de vaso sanitários', 15),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria dos Telhados', 16),
  (v_tmpl_id, 'Spa Pitanguinha', 'Vistoria de tampa de vaso', 17),
  (v_tmpl_id, 'Anexo Pitanguinha', 'Vistoria de tomadas', 18),
  (v_tmpl_id, 'Anexo Pitanguinha', 'Vistoria de Roteador de internet', 19),
  (v_tmpl_id, 'Anexo Pitanguinha', 'Vistoria de iluminação', 20),
  (v_tmpl_id, 'Anexo Pitanguinha', 'Vistoria de abajur', 21),
  (v_tmpl_id, 'Anexo Pitanguinha', 'Vistoria de Ar Condicionado', 22),
  (v_tmpl_id, 'Anexo Pitanguinha', 'Vistoria dos Telhados', 23),
  (v_tmpl_id, 'Anexo Pitanguinha', 'Vistoria dos ferrolhos', 24),
  (v_tmpl_id, 'Sala de mapas', 'Vistoria de tomadas', 25),
  (v_tmpl_id, 'Sala de mapas', 'Vistoria de Roteador de internet', 26),
  (v_tmpl_id, 'Sala de mapas', 'Vistoria de iluminação', 27),
  (v_tmpl_id, 'Sala de mapas', 'Vistoria de abajur', 28),
  (v_tmpl_id, 'Sala de mapas', 'Vistoria de Ar Condicionado', 29),
  (v_tmpl_id, 'Sala de mapas', 'Vistoria dos Telhados', 30),
  (v_tmpl_id, 'Sala de mapas', 'Vistoria dos ferrolhos', 31),
  (v_tmpl_id, 'Lounge', 'Vistoria de tomadas', 32),
  (v_tmpl_id, 'Lounge', 'Vistoria de Roteador de internet', 33),
  (v_tmpl_id, 'Lounge', 'Vistoria de iluminação', 34),
  (v_tmpl_id, 'Lounge', 'Vistoria de ventiladores', 35),
  (v_tmpl_id, 'Lounge', 'Vistoria de abajur', 36),
  (v_tmpl_id, 'Lounge', 'Vistoria de Ar Condicionado', 37),
  (v_tmpl_id, 'Lounge', 'Vistoria dos ferrolhos', 38),
  (v_tmpl_id, 'Lounge', 'Vistoria dos Telhados', 39),
  (v_tmpl_id, 'Lounge', 'Vistoria dos móveis', 40),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de tomadas', 41),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de iluminação', 42),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de Pias/sifão e válvula', 43),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de torneiras / quente e fria', 44),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de registros', 45),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de fluxo de água nas torneiras', 46),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de fluxo de água dos chuveiros', 47),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria ducha higiênicas', 48),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de vaso sanitários', 49),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria de tampa de vaso', 50),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria Fechaduras', 51),
  (v_tmpl_id, 'Banheiro Nazaré', 'Vistoria dos Telhados', 52),
  (v_tmpl_id, 'Armazém', 'Vistoria de tomadas', 53),
  (v_tmpl_id, 'Armazém', 'Vistoria de Roteador de internet', 54),
  (v_tmpl_id, 'Armazém', 'Vistoria de iluminação', 55),
  (v_tmpl_id, 'Armazém', 'Vistoria de ventiladores', 56),
  (v_tmpl_id, 'Armazém', 'Vistoria de abajur', 57),
  (v_tmpl_id, 'Armazém', 'Vistoria de Ar Condicionado', 58),
  (v_tmpl_id, 'Armazém', 'Vistoria dos ferrolhos', 59),
  (v_tmpl_id, 'Armazém', 'Vistoria dos móveis', 60),
  (v_tmpl_id, 'Armazém', 'Vistoria dos Telhados', 61),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de tomadas', 62),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de Roteador de internet', 63),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de iluminação', 64),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de ventiladores', 65),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de abajur', 66),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria dos ferrolhos', 67),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria dos móveis', 68),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de Pias/sifão e válvula', 69),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de torneiras', 70),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de registros', 71),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de fluxo de água nas torneiras/quente e fria', 72),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria ducha higiênicas', 73),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de vaso sanitários', 74),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria de tampa de vaso', 75),
  (v_tmpl_id, 'Restaurante Vi', 'Vistoria dos Telhados', 76),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de tomadas', 77),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de Roteador de internet', 78),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de iluminação', 79),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de ventiladores', 80),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de abajur', 81),
  (v_tmpl_id, 'Bar Vi', 'Vistoria dos ferrolhos', 82),
  (v_tmpl_id, 'Bar Vi', 'Vistoria dos móveis', 83),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de Pias/sifão e válvula', 84),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de torneiras', 85),
  (v_tmpl_id, 'Bar Vi', 'Vistoria dos Telhados', 86),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de registros', 87),
  (v_tmpl_id, 'Bar Vi', 'Vistoria do filtro de carvão ativado', 88),
  (v_tmpl_id, 'Bar Vi', 'Vistoria de dreno maquina de gelo', 89),
  (v_tmpl_id, 'Cozinha', 'Vistoria de tomadas', 90),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Roteador de internet', 91),
  (v_tmpl_id, 'Cozinha', 'Vistoria de iluminação', 92),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Ar Condicionado', 93),
  (v_tmpl_id, 'Cozinha', 'Vistoria das cortinas de vento', 94),
  (v_tmpl_id, 'Cozinha', 'Vistoria do filtro de carvão ativado', 95),
  (v_tmpl_id, 'Cozinha', 'Vistoria de Pias/sifão e válvula', 96),
  (v_tmpl_id, 'Cozinha', 'Vistoria de torneiras', 97),
  (v_tmpl_id, 'Cozinha', 'Vistoria dos Telhados', 98),
  (v_tmpl_id, 'Cozinha', 'Vistoria de registros', 99),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de tomadas', 100),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de iluminação', 101),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de Pias/sifão e válvula', 102),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de torneiras / quente e fria', 103),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de registros', 104),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de fluxo de água nas torneiras', 105),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de fluxo de água dos chuveiros', 106),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria ducha higiênicas', 107),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de vaso sanitários', 108),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria de tampa de vaso', 109),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria Fechaduras', 110),
  (v_tmpl_id, 'Banheiro Spa', 'Vistoria dos Telhados', 111);

END $$;
